using System.Reflection;
[assembly: System.Reflection.AssemblyTitle("BMTune")]
[assembly: System.Reflection.AssemblyConfiguration("")]
[assembly: System.Runtime.CompilerServices.RuntimeCompatibility(WrapNonExceptionThrows=true)]
[assembly: System.Reflection.AssemblyDescription("Built in 2017 by the property of BMDevs.")]
[assembly: System.Runtime.InteropServices.ComVisible(false)]
[assembly: System.Reflection.AssemblyCompany("BMDevs")]
[assembly: System.Security.AllowPartiallyTrustedCallers]
[assembly: System.Security.SecurityRules(System.Security.SecurityRuleSet.Level1)]
[assembly: System.Runtime.InteropServices.Guid("8b9822db-f66e-4d41-ad86-0f32abd22b96")]
[assembly: System.Reflection.AssemblyFileVersion("1.0.0.0")]
[assembly: System.Reflection.AssemblyCopyright("Copyright \x00a9 2021 by BMDevs. All rights reserved. Contact the author at bouletmarc@hotmail.com")]
[assembly: System.Reflection.AssemblyProduct("BMTune")]
[assembly: System.Runtime.CompilerServices.CompilationRelaxations(8)]
[assembly: System.Reflection.AssemblyTrademark("")]
[assembly: AssemblyVersion("1.0.0.0")]

